services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app-network
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests

  admin-frontend:
    build: ./admin-frontend
    container_name: admin-frontend
    env_file:
      - ./admin-frontend/.env.local
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - app-network

  user-frontend:
    build: ./user-frontend
    container_name: user-frontend
    env_file:
      - ./user-frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: